FROM busybox:latest as data

WORKDIR /data
COPY data/img/christies/s128/christies.tar.gz /data/

# Deploy image
FROM gcr.io/deeplearning-platform-release/tf2-gpu.2-2:latest

ENV SERVICE_EMAIL=paap-crawl@art-auction-prices.iam.gserviceaccount.com
ENV GCLOUD_PROJECT=art-auction-prices

RUN gcloud config set project $GCLOUD_PROJECT

# Install graphviz for plotting models
RUN apt-get update && apt-get -y install graphviz

WORKDIR /build
# create venv and install requirements
ADD nn/requirements.txt /build/requirements.txt
RUN python -m venv dcec
RUN dcec/bin/pip install -r requirements.txt

# Add data
RUN mkdir data
COPY --from=data /data/christies.tar.gz /build/data/
RUN tar -xzf /build/data/christies.tar.gz
RUN rm /build/data/christies.tar.gz

# Add code
ADD nn/dcec_paint/*.py /build/
ADD nn/dcec_paint/run_model.sh /build/run_model.sh

RUN mkdir results

CMD ["/build/dcec/bin/python", "DCEC.py"]
